package hu.fourdsoft.memorygame.common.data.model;

//default package
//Generated 2017.07.31. 11:25:01 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.io.Serializable;
import java.util.Date;

/**
 * Result generated by hbm2java
 */
@Entity
@Table(name = "RESULT_DATA")
@NamedQuery(name = "ResultData.findAll", query = "SELECT r FROM ResultData r")
@SequenceGenerator(name = "RESULT_DATA_SEQ", sequenceName = "RESULT_DATA_SEQ", initialValue = 1, allocationSize = 0)
public class ResultData implements Serializable {
	private static final long serialVersionUID = 1L;

	private long id;
	private long userId;
	private Date resultDate;
	private long seconds;

	public ResultData() {
	}

	public ResultData(long id, long userId, Date resultDate, long seconds) {
		this.id = id;
		this.userId = userId;
		this.resultDate = resultDate;
		this.seconds = seconds;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "RESULT_DATA_SEQ")

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "USER_ID", nullable = false, precision = 22, scale = 0)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "RESULT_DATE", nullable = false, length = 7)
	public Date getResultDate() {
		return this.resultDate;
	}

	public void setResultDate(Date resultDate) {
		this.resultDate = resultDate;
	}

	@Column(name = "SECONDS", nullable = false, precision = 22, scale = 0)
	public long getSeconds() {
		return this.seconds;
	}

	public void setSeconds(long seconds) {
		this.seconds = seconds;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (o == null || getClass() != o.getClass())
			return false;

		ResultData result = (ResultData) o;

		if (id != result.id)
			return false;
		if (seconds != result.seconds)
			return false;
		if (resultDate != null ? !resultDate.equals(result.resultDate) : result.resultDate != null)
			return false;

		return true;
	}

	@Override
	public int hashCode() {
		int result = (int) (id ^ (id >>> 32));
		result = 31 * result + (resultDate != null ? resultDate.hashCode() : 0);
		result = 31 * result + (int) (seconds ^ (seconds >>> 32));
		return result;
	}

	@Override
	public String toString() {
		return "Result [id=" + id + ", resultDate=" + resultDate + ", seconds=" + seconds + ", userId=" + userId + "]";
	}

}
